### ISSUE TITLE
ExtractTextPlugin support

### ISSUE THREAD

**Issue by stepet80** [leftstick/unminified-webpack-plugin#12]
Hello,

I am using this plugin to create both normal files and min files.
I am also using extract-text-plugin to extract the css into a separate file like so:

  {
                test: /\.css$/,
                // use extract text plugin to extract css to separate file
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: [{
                        loader: "css-loader",
                        options: {
                            // do url parsing
                            url: true,
                            minimize: true,
                            sourceMap: true                            
                        }
                    }]
                })
            },
Obviously the system to create both min and normal files doesn't work with this.
Is it possible to use extrat-text-oplugin and to have both minified and not-minified css files?
Or do you know another way.

Thanks in advance

**Comment by leftstick** [comment]
The thing is, if you minify css by `css-loader`, we can do nothing with `unminified-webpack-plugin`, since the css shall be minified while passed to the plugin system.

I will think about a way to have css working well with `extract-text-webpack-plugin`, but definitely not with `css-loader`, maybe [optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin)

**Comment by leftstick** [comment]
@stepet80 published a new version `1.3.0. `check [working-example](https://github.com/leftstick/unminified-webpack-plugin/blob/master/example/css-pack/README.md) for configuration

**Comment by stepet80** [comment]
Ok now it works. Thanks a lot!
