### ISSUE TITLE
Support for webpack-parallel-uglify-plugin

### ISSUE THREAD

**Issue by AndyOGo** [leftstick/unminified-webpack-plugin#7]
Is it possible to support https://www.npmjs.com/package/webpack-parallel-uglify-plugin?

**Comment by leftstick** [comment]
It's a bit hard, since `webpack-parallel-uglify-plugin` compress all the `compilation.assets` which is different from `UglifyJsPlugin`.

Which means, `webpack-parallel-uglify-plugin` will compress the file including the one i created via `unminified-webpack-plugin`.

And i don't know if there is a way to tell `webpack-parallel-uglify-plugin` ignoring the asset generated by `unminified-webpack-plugin`. I think you may need help from `webpack-parallel-uglify-plugin`, if it is possible to retrieve the same asset collection as `UglifyJsPlugin`

**Comment by AndyOGo** [comment]
@leftstick thanks you very much for your quick answer 👍

**Comment by kfeinUI** [comment]
Have been doing some experimentation and exploration of the combination of these 2 plugins. What I've found upon deeper inspection of webpack-parallel-uglify-plugin is that it loops over compilation.assets to process each js entry. additionalChuckAssets are left out. It additionally skips much of the functionality of UglifyJSPlugin. Nice performance boost, but falls short for my requirements.

A better solution would probably be to write a plugin that wraps / leverages the existing plugin to parallelize it while still maintaining consistency. That or try pushing through an enhancement to UglifyJsPlugin itself (does seem like a reasonable option).

**Comment by leftstick** [comment]
@kfeinUI  sorry, that i can not help on it due to heathy issue, can you help? PR is always welcomed^^

**Comment by w0rse** [comment]
As noted here (https://github.com/tradingview/webpack-uglify-parallel/issues/2), unminified plugin checks for exact instances of UglifyJsPlugin in plugins list. Which UglifyJsParallelPlugin is of course not. Can we somehow weaken the check? Probably adding some properties to plugins that want to look like UglifyJsPlugin.

**Comment by leftstick** [comment]
not sure if it is still a valid issue, close for now. 
Feel free to reopen it if you have further issue
